server:
  port: 8888
spring:
  activemq:
    broker-url: tcp://192.168.179.4:61616 #自己的MQ服务器地址
    user: admin #username
    password: admin #password
  jms:
    pub-sub-domain: false  #发布订阅 false指的是队列,true指的是topic
#自定义队列名称
myqueue: springboot-active-queue