server:
  port: 9092
spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: false #true表示使用连接池，false则连接服务器
    pool:
      enabled: true  #true表示使用连接池，false表示每发送一条数据创建一个连接
      max-connections: 10 #连接池的最大连接数
      idle-timeout: 30000 #空闲的连接过期时间，默认是30s